version: '3.8'

services:
  # Сервис для PostgreSQL
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Сервис для бэкенда
  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      IP: ${IP}
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Сервис для фронтенда
  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "8080:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

# Том для хранения данных PostgreSQL
volumes:
  postgres_data: